// Glossário DE/PARA das colunas do legado (Dexie) para o esquema PostgreSQL 100% em português.
//
// Formato:  coluna_legado: 'coluna_pt'                  -> coluna simples
//           coluna_legado: ['coluna_pt', 'tabela_legado'] -> chave estrangeira para a tabela (nome legado)
//           coluna_legado: null                          -> não migra (metadado do Dexie / enchimento)
//
// Convenções (directiva de 2026-09-29):
//  - snake_case em português, ortografia do AO90 nas colunas (ativo, projeto, atualizado);
//    os nomes de tabela seguem a matriz contratual literalmente (ex.: efectividade_assiduidade).
//  - Todas as variantes de tenant (company_id, rh_company_id, crm_company_id, ...) -> empresa_id.
//  - Carimbos temporais Laravel: criado_em / atualizado_em / eliminado_em.
//  - Onde o dicionário da directiva (secção 3) fixa um nome, esse nome prevalece
//    (diario_id, nota_demonstracao_id, reconciliacao_codigo, cargo_funcao_id, tipo_organizacao_id).
//  - Colunas cujo destino depende da tabela estão em SOBREPOSICOES (abaixo).

export const GLOSSARIO = {
  $types: null,
  is_master_data: null,
  id: 'id',

  // ── Tenant ────────────────────────────────────────────────────────────────
  company_id: ['empresa_id', 'companies'],
  ad_company_id: ['empresa_id', 'companies'],
  crm_company_id: ['empresa_id', 'companies'],
  fe_company_id: ['empresa_id', 'companies'],
  hotel_company_id: ['empresa_id', 'companies'],
  lav_company_id: ['empresa_id', 'companies'],
  orc_company_id: ['empresa_id', 'companies'],
  org_company_id: ['empresa_id', 'companies'],
  pa_company_id: ['empresa_id', 'companies'],
  pos_company_id: ['empresa_id', 'companies'],
  rh_company_id: ['empresa_id', 'companies'],
  report_company_id: ['empresa_id', 'companies'],
  scope_company_id: ['empresa_id', 'companies'],
  holding_company_id: ['empresa_holding_id', 'companies'],
  member_company_id: ['empresa_membro_id', 'companies'],
  source_company_id: ['empresa_origem_id', 'companies'],
  intragroup_company_id: ['empresa_intragrupo_id', 'companies'],

  // ── Auditoria / carimbos ──────────────────────────────────────────────────
  created_at: 'criado_em', created_on: 'criado_em', criado_em: 'criado_em', criada_em: 'criado_em',
  created_by: 'criado_por', criado_por: 'criado_por',
  updated_at: 'atualizado_em', atualizado_em: 'atualizado_em', actualizado_em: 'atualizado_em',
  updated_by: 'atualizado_por', atualizado_por: 'atualizado_por', actualizado_por: 'atualizado_por',
  deleted_at: 'eliminado_em',
  aberto_em: 'aberto_em', aberto_por: 'aberto_por', opened_at: 'aberto_em',
  closed_at: 'fechado_em', fechado_em: 'fechado_em', fechada_em: 'fechado_em',
  closed_by: 'fechado_por', fechado_por: 'fechado_por',
  concluida: 'concluida', concluida_em: 'concluida_em', concluida_por: 'concluida_por',
  decidido_em: 'decidido_em', lancado_em: 'lancado_em', lancado_por: 'lancado_por',
  posted_at: 'contabilizado_em', posted_by: 'contabilizado_por',
  reaberto_em: 'reaberto_em', reaberto_por: 'reaberto_por',
  registado_em: 'registado_em', registado_por: 'registado_por',
  submetida_em: 'submetida_em', ultima_actividade_em: 'ultima_atividade_em',
  assigned_at: 'atribuido_em', assigned_by: 'atribuido_por',
  delivered_at: 'entregue_em', received_at: 'recebido_em', received_by: 'recebido_por',
  run_at: 'executado_em', timestamp: 'ocorrido_em',
  em: 'em', por: 'por',

  // ── Identificação / genéricos ─────────────────────────────────────────────
  code: 'codigo', codigo: 'codigo', name: 'nome', nome: 'nome', short_name: 'nome_abreviado',
  description: 'descricao', descricao: 'descricao', titulo: 'titulo', key: 'chave', chave: 'chave',
  type: 'tipo', tipo: 'tipo', kind: 'natureza_registo', period_id: 'periodo_id', status: 'estado', estado: 'estado', state: 'estado_fluxo',
  notes: 'observacoes', observacoes: 'observacoes', notas: 'notas', notas_incluir: 'notas_incluir',
  details: 'detalhes', dados: 'dados', config: 'configuracao', extras: 'extras', meta: 'meta',
  color: 'cor', cor: 'cor', ordem: 'ordem', seq_order: 'ordem_sequencia', uid: 'uid',
  legacy_id: 'id_legado', import_id: 'importacao_codigo', batch_id: 'lote_codigo', batch_ref: 'referencia_lote',
  table_name: 'nome_tabela', module: 'modulo', module_context: 'contexto_modulo', action: 'acao',
  record_id: 'registo_id', source: 'fonte_dados', fonte: 'fonte', origem: 'origem',
  system_origin: 'sistema_origem', software: 'software', versao: 'versao',
  template: 'modelo', history: 'historico_alteracoes', historico: 'historico',
  keywords: 'palavras_chave', principal: 'principal', grupo: 'grupo', area: 'area', sector: 'setor',
  is_active: 'ativo', activo: 'ativo', is_default: 'predefinido', is_blocked: 'bloqueado',
  is_imported: 'importado', is_validated: 'validado', urgent: 'urgente', automatica: 'automatica',
  detectada: 'detectada', value_input: 'valor_introduzido',

  // ── Empresa / morada / contactos ──────────────────────────────────────────
  nif: 'nif', nif_imported: 'nif_importado', logo: 'logotipo', address: 'endereco', endereco: 'endereco',
  morada: 'morada', street: 'rua', door_number: 'numero_porta', neighborhood: 'bairro', bairro: 'bairro',
  city: 'cidade', commune: 'comuna', municipality: 'municipio', municipio: 'municipio',
  province: 'provincia', provincia: 'provincia', country: 'pais', pais_padrao: 'pais_padrao',
  postal_code: 'codigo_postal', location: 'localizacao', phone: 'telefone', telefone: 'telefone',
  telefone_alternativo: 'telefone_alternativo', fax: 'fax', email: 'email', website: 'website',
  crc: 'numero_registo_comercial', doc_footer: 'rodape_documento', ai_rules: 'regras_ia',
  inss_patronal: 'taxa_inss_patronal', inss_trabalhador: 'taxa_inss_trabalhador',
  is_consolidation: 'e_consolidacao', consolidation_currency: 'moeda_consolidacao',
  consolidation_date_end: 'data_fim_consolidacao', presentation_currency: 'moeda_apresentacao',
  estabelecimentos: 'estabelecimentos', stock_exchange: 'bolsa_valores', ticker_symbol: 'simbolo_bolsa',

  // ── Utilizadores / perfis ─────────────────────────────────────────────────
  username: 'nome_utilizador', user: 'nome_utilizador', password: null,
  password_hash: 'hash_password', password_salt: 'salt_password', password_algo: 'algoritmo_password',
  role: 'papel', profile_id: ['perfil_utilizador_id', 'user_profiles'],
  allowed_companies: 'empresas_permitidas', allowed_modules: 'modulos_permitidos',
  permissions: 'permissoes', colaboradores: 'colaboradores', utilizadores: 'utilizadores',
  utilizador_responsavel: 'utilizador_responsavel',

  // ── Datas ─────────────────────────────────────────────────────────────────
  date: 'data', data: 'data', doc_date: 'data_documento', data_documento: 'data_documento',
  orig_doc_date: 'data_documento_original', entry_date: 'data_lancamento', due_date: 'data_vencimento',
  delivery_date: 'data_entrega', promised_date: 'data_prometida', expected_date: 'data_prevista',
  data_prevista: 'data_prevista', start_date: 'data_inicio', data_inicio: 'data_inicio',
  end_date: 'data_fim', date_end: 'data_fim', data_fim: 'data_fim', data_limite: 'data_limite',
  data_fecho_prevista: 'data_fecho_prevista', open_date: 'data_abertura', close_date: 'data_fecho',
  acquisition_date: 'data_aquisicao', execution_date: 'data_execucao', run_date: 'data_execucao',
  audit_date: 'data_conferencia', upload_date: 'data_carregamento', rate_date: 'data_taxa',
  valid_from: 'valido_de', valid_to: 'valido_ate', valid_until: 'valido_ate', validity_days: 'dias_validade',
  checkin_at: 'entrada_em', checkout_at: 'saida_em', planned_checkout_at: 'saida_prevista_em',
  etapa_desde: 'etapa_desde', apurado_ate: 'apurado_ate',
  year: 'ano', ano: 'ano', month: 'mes', mes: 'mes', month_year: 'mes_ano',
  report_year: 'ano_relatorio', periodo: 'periodo', periodo_ref: 'periodo_referencia',
  acc_period: 'periodo_contabil',

  // ── Contabilidade ─────────────────────────────────────────────────────────
  account_code: 'codigo_conta', account_name: 'nome_conta', account_number: 'numero_conta',
  account_fin: 'conta_financeira', account_debit: 'conta_debito', account_credit: 'conta_credito',
  account_cost: 'conta_custo', account_expense: 'conta_gasto', account_sale: 'conta_venda',
  account_purchase: 'conta_compra', account_purchase_clearing: 'conta_compra_transitoria',
  account_inventory: 'conta_inventario', account_asset: 'conta_ativo',
  account_accumulated: 'conta_amortizacao_acumulada', account_loss: 'conta_perda',
  account_shortage: 'conta_quebra', account_surplus: 'conta_sobra', account_operator: 'conta_operador',
  account_iva: 'conta_iva', account_iva_dedutivel: 'conta_iva_dedutivel', account_iva_liquidado: 'conta_iva_liquidado',
  commission_account: 'conta_comissao', regularization_account: 'conta_regularizacao',
  regularization_account_name: 'nome_conta_regularizacao', target_account: 'conta_destino',
  transit_account: 'conta_transitoria', fx_reserve_account: 'conta_reserva_cambial',
  elim_diff_account: 'conta_diferenca_eliminacao', elim_enabled: 'eliminacao_ativa',
  elim_exclude_prefixes: 'prefixos_excluidos_eliminacao', conta_balanco: 'conta_balanco',
  conta_resultado: 'conta_resultado', contas: 'contas', payment_accounts: 'contas_pagamento',
  journal_id: ['diario_id', 'journals'], posting_journal_id: ['diario_contabilizacao_id', 'journals'],
  journal_code: 'codigo_diario', journal_line_id: ['lancamento_contabil_id', 'journal_lines'],
  journal_entry_ref: 'referencia_lancamento', lan_number: 'numero_lan',
  posting_lans: 'lans_contabilizacao', posting_status: 'estado_contabilizacao',
  pos_posting_lans: 'pos_lans_contabilizacao', is_posted: 'contabilizado',
  type_dc: 'tipo_dc', nature: 'natureza', natureza: 'natureza',
  demo_note_id: ['nota_demonstracao_id', 'demo_notes'],
  cashflow_note_id: ['nota_fluxo_caixa_id', 'cashflow_notes'],
  reconciliation_id: 'reconciliacao_codigo', match_type: 'tipo_correspondencia',
  external_balance: 'saldo_externo', external_name: 'nome_externo',
  consolidation_run_id: ['execucao_consolidacao_id', 'consolidation_runs'],
  consolidation_type: 'tipo_consolidacao', last_run_id: ['ultima_execucao_id', 'consolidation_runs'],
  group_id: ['grupo_consolidacao_id', 'consolidation_groups'],
  source_line_id: 'linha_origem_id', value_kz_origem: 'valor_kz_origem',
  documento_em_balanco: 'documento_em_balanco', notas_perda: 'notas_perda',
  ad_item_id: ['item_acrescimo_diferimento_id', 'ad_items'],
  opening_balance: 'saldo_abertura', closing_balance: 'saldo_fecho', physical_balance: 'saldo_fisico',

  // ── Documentos / origem ───────────────────────────────────────────────────
  doc_number: 'numero_documento', doc_type: 'tipo_documento', doc_ref: 'referencia_documento',
  doc_url: 'url_documento', reference: 'referencia', documento: 'documento',
  invoice_number: 'numero_fatura', receipt_number: 'numero_recibo', order_number: 'numero_encomenda',
  delivery_number: 'numero_entrega', sale_number: 'numero_venda',
  source_doc_id: 'documento_origem_id', source_doc_type: 'tipo_documento_origem',
  source_id: 'origem_id', source_type: 'tipo_origem', source_module: 'modulo_origem',
  generated_doc_id: 'documento_gerado_id', related_doc_id: 'documentos_relacionados',
  parent_type: 'tipo_documento_origem', entity_type: 'tipo_entidade',
  file_name: 'nome_ficheiro', file_data: 'conteudo_ficheiro', mime_type: 'tipo_mime',
  image_base64: 'imagem_base64', prazo_documento_dias: 'prazo_documento_dias',

  // ── Valores monetários / quantidades ──────────────────────────────────────
  value: 'valor', valor: 'valor', valores: 'valores', value_kz: 'valor_kz', value_currency: 'valor_moeda',
  amount: 'montante', amount_gross: 'montante_bruto', amount_net: 'montante_liquido', amount_paid: 'montante_pago',
  total: 'total', total_value: 'valor_total', total_value_kz: 'valor_total_kz',
  total_value_currency: 'valor_total_moeda', total_amount: 'montante_total',
  total_amount_currency: 'montante_total_moeda', total_currency: 'total_moeda', total_kz: 'total_kz',
  total_net: 'total_liquido', total_net_currency: 'total_liquido_moeda',
  total_tax: 'total_imposto', total_tax_currency: 'total_imposto_moeda',
  total_gross: 'total_bruto', total_gross_currency: 'total_bruto_moeda',
  total_discount: 'total_desconto', subtotal: 'subtotal', line_total: 'total_linha',
  totals: 'totais', totais: 'totais', totals_by_method: 'totais_por_metodo', total_fecho: 'total_fecho',
  total_physical: 'total_fisico', total_system: 'total_sistema', total_sales: 'total_vendas',
  paid_amount: 'valor_pago', pending_amount: 'valor_pendente', pendente_no_fecho: 'pendente_no_fecho',
  price: 'preco', unit_price: 'preco_unitario', preco_unitario: 'preco_unitario',
  unit_price_currency: 'preco_unitario_moeda', unit_cost_kz: 'custo_unitario_kz',
  pricePerDay: 'preco_por_dia', pricePerHour: 'preco_por_hora', service_prices: 'precos_servico',
  cost: 'custo', custom_cost: 'custo_personalizado', contract_value: 'valor_contrato',
  calculated_value: 'valor_calculado', discount: 'desconto', discount_pct: 'percentagem_desconto',
  tax_rate: 'taxa_imposto', tax_value: 'valor_imposto', tax_currency: 'imposto_moeda',
  commission: 'comissao', rate: 'taxa', annual_rate: 'taxa_anual', percentage: 'percentagem',
  current_pct: 'percentagem_atual', previous_pct: 'percentagem_anterior', execution_pct: 'percentagem_execucao',
  inflacao_pct: 'inflacao_pct', crescimento_custos_pct: 'crescimento_custos_pct',
  crescimento_proveitos_pct: 'crescimento_proveitos_pct',
  quantity: 'quantidade', quantidade: 'quantidade', quantidade_considerada: 'quantidade_considerada',
  stock_qty: 'quantidade_stock', delivered_qty: 'quantidade_entregue', billed_qty: 'quantidade_faturada',
  invoiced_qty: 'quantidade_faturada', received_qty: 'quantidade_recebida',
  counted_quantity: 'quantidade_contada', system_quantity: 'quantidade_sistema', final_quantity: 'quantidade_final',
  difference: 'diferenca', diferenca: 'diferenca', deviation: 'desvio', deviation_status: 'estado_desvio',
  deviation_tolerance: 'tolerancia_desvio', minimo: 'minimo', maximo: 'maximo', target: 'alvo',
  unit: 'unidade', unidade: 'unidade', decimals: 'casas_decimais', symbol: 'simbolo',

  // ── Moeda / câmbio ────────────────────────────────────────────────────────
  currency: 'codigo_moeda', exchange_rate: 'taxa_cambio', exchange_rate_manual: 'taxa_cambio_manual',
  exchange_rate_id: ['taxa_cambio_id', 'exchange_rates'], bai_buy: 'taxa_compra_bai', bai_sell: 'taxa_venda_bai',
  fx_bal_cur: 'cambial_saldo_moeda', fx_bal_kz: 'cambial_saldo_kz', fx_doc_currency: 'cambial_moeda_documento',
  fx_fat_por_receber_kz: 'cambial_faturado_por_receber_kz', fx_fat_por_receber_qty: 'cambial_faturado_por_receber_qtd',
  fx_rec_por_faturar_kz: 'cambial_recebido_por_faturar_kz', fx_rec_por_faturar_qty: 'cambial_recebido_por_faturar_qtd',
  fx_q1: 'cambial_q1', fx_q2: 'cambial_q2', fx_v1: 'cambial_v1', fx_v2: 'cambial_v2',

  // ── Terceiros / vendas / compras ──────────────────────────────────────────
  third_party_id: ['terceiro_id', 'third_parties'], customer_id: ['cliente_id', 'third_parties'],
  supplier_id: ['fornecedor_id', 'third_parties'], default_customer_id: ['cliente_padrao_id', 'third_parties'],
  guest_customer_id: ['cliente_hospede_id', 'third_parties'],
  sale_id: ['venda_id', 'sales'], related_sale_id: ['venda_relacionada_id', 'sales'],
  source_sale_id: ['venda_origem_id', 'sales'], sales_order_id: ['encomenda_venda_id', 'sales'],
  receipt_id: ['recibo_venda_id', 'receipts'], product_id: ['produto_id', 'products'],
  room_product_id: ['produto_quarto_id', 'products'],
  purchase_request_id: ['pedido_compra_id', 'purchase_requests'], request_id: ['pedido_compra_id', 'purchase_requests'],
  quote_id: ['cotacao_compra_id', 'purchase_quotes'], warehouse_id: ['armazem_id', 'warehouses'],
  requester_name: 'nome_requerente', requester_employee_id: ['colaborador_requerente_id', 'employees'],
  delivery: 'entrega', delivery_location: 'local_entrega', receiving_area: 'area_rececao',
  payment_method: 'meio_pagamento', payment_methods: 'meios_pagamento', payment_mode: 'modo_pagamento',
  payment_reference: 'referencia_pagamento', payment_schedule: 'plano_pagamentos',
  payment_terms: 'condicoes_pagamento', hide_payment_methods: 'ocultar_meios_pagamento',
  invoice_ids: 'faturas_ids', order_ids: 'encomendas_ids', hotel_stay_ids: 'estadias_hotel_ids',
  invoice_mode: 'modo_faturacao', items: 'itens', itens: 'itens', lines: 'linhas', linhas: 'linhas',
  item_key: 'chave_item', has_sales: 'tem_vendas', has_service: 'tem_servico',
  is_inventory: 'movimenta_stock', is_service: 'e_servico', is_asset: 'e_ativo_imobilizado', is_room: 'e_quarto',
  fe_isencao: 'codigo_isencao_fe', fe_tipo_operacao: 'tipo_operacao_fe', fe_unidade: 'unidade_fe',
  isencao_padrao: 'isencao_padrao', counters: 'contadores', session_counters: 'contadores_sessao',
  sales_count: 'numero_vendas', vendas: 'vendas', crm_opportunity_id: ['oportunidade_crm_id', 'crm_opportunities'],

  // ── Tesouraria / caixa / POS ──────────────────────────────────────────────
  treasury_doc_id: ['documento_tesouraria_id', 'treasury_documents'],
  bank_id: ['banco_id', 'banks'], iban: 'iban', swift: 'swift',
  cash_session_id: ['sessao_caixa_id', 'cash_sessions'], cash_line_id: ['movimento_caixa_id', 'cash_lines'],
  cash_counted: 'numerario_contado', cash_counts: 'contagens_numerario', cash_expected: 'numerario_esperado',
  cash_sales: 'vendas_numerario', denominations: 'denominacoes', change: 'troco',
  operator: 'operador', operator_name: 'nome_operador', operator_id: 'operador_id',
  opening_float: 'fundo_maneio_abertura', default_float: 'fundo_maneio_padrao',
  pos_session_id: ['sessao_pos_id', 'pos_sessions'], pos_terminal_id: ['terminal_pos_id', 'pos_terminals'],
  terminal_id: ['terminal_pos_id', 'pos_terminals'], pos_terminal_code: 'codigo_terminal_pos',
  terminal_code: 'codigo_terminal', terminal_name: 'nome_terminal', pos_payments: 'pos_pagamentos',
  pos_change: 'pos_troco', pos_operator: 'pos_operador', session_code: 'codigo_sessao',
  reception_session_id: ['sessao_rececao_id', 'pos_sessions'], closed_session_id: ['sessao_fecho_id', 'pos_sessions'],
  pm_id: 'meio_pagamento_codigo', settlement_status: 'estado_liquidacao', tpa_closes: 'fechos_tpa',
  z_counters: 'contadores_z', z_number: 'numero_z', transfers: 'transferencias',
  method: 'metodo', metodo: 'metodo', mode: 'modo', entrada: 'entrada', saida: 'saida',

  // ── Hotelaria / lavandaria ────────────────────────────────────────────────
  guest_name: 'nome_hospede', guests_count: 'numero_hospedes', room_name: 'nome_quarto',
  hotel_checkin_time: 'hotel_hora_entrada', hotel_checkout_time: 'hotel_hora_saida',
  hotel_hour_block: 'hotel_bloco_horas', hotel_hour_block_from: 'hotel_bloco_horas_de',
  hotel_hour_block_to: 'hotel_bloco_horas_ate', hotel_late_tolerance_min: 'hotel_tolerancia_atraso_min',
  late_choice: 'opcao_atraso', minHours: 'horas_minimas',
  lav_active: 'lavandaria_ativa', lav_group: 'lavandaria_grupo', lav_unit: 'lavandaria_unidade',
  lav_lead_days: 'lavandaria_dias_entrega', lav_price_kg: 'lavandaria_preco_kg',
  lav_price_piece: 'lavandaria_preco_peca', lav_requires_quote: 'lavandaria_requer_orcamento',
  lav_ft_counters: 'lavandaria_contadores_ft', lav_os_counters: 'lavandaria_contadores_os',
  lav_rc_counters: 'lavandaria_contadores_rc', lav_order_id: ['pedido_lavandaria_id', 'lav_orders'],
  lav_order_number: 'numero_pedido_lavandaria', fabric: 'tecido', pickup: 'recolha',
  assigned_employee_id: ['colaborador_atribuido_id', 'employees'], assigned_name: 'nome_atribuido',

  // ── Activos ───────────────────────────────────────────────────────────────
  asset_id: ['ativo_imobilizado_id', 'fixed_assets'], acquisition_value: 'valor_aquisicao',
  accumulated_depreciation: 'amortizacao_acumulada', accumulated_dep_initial: 'amortizacao_acumulada_inicial',
  accumulated_end_year: 'acumulado_fim_ano', residual_value: 'valor_residual', useful_life: 'vida_util',
  remaining_life: 'vida_util_restante', default_useful_life: 'vida_util_padrao', fixed_quota: 'quota_fixa',
  from_cc_id: ['centro_custo_origem_id', 'cost_centers'], to_cc_id: ['centro_custo_destino_id', 'cost_centers'],

  // ── Estrutura analítica ───────────────────────────────────────────────────
  business_unit_id: ['unidade_negocio_id', 'business_units'], bu_id: ['unidade_negocio_id', 'business_units'],
  cost_center_id: ['centro_custo_id', 'cost_centers'], cc_id: ['centro_custo_id', 'cost_centers'],

  // ── Projectos ─────────────────────────────────────────────────────────────
  project_id: ['projeto_id', 'projects'], project_code: 'codigo_projeto',
  task_id: ['tarefa_projeto_id', 'project_tasks'], parent_task_id: ['tarefa_pai_id', 'project_tasks'],
  milestone_id: ['marco_projeto_id', 'project_milestones'], team_id: ['equipa_projeto_id', 'project_teams'],
  requisition_id: ['requisicao_material_projeto_id', 'project_requisitions'],
  review_id: ['revisao_mensal_projeto_id', 'project_reviews'],
  org_node_id: ['no_organigrama_projeto_id', 'project_org_nodes'],
  responsavel_member_id: ['membro_responsavel_id', 'project_team_members'],
  assigned_to_id: 'atribuido_a_id', allocated_hours: 'horas_alocadas', assignment_note: 'nota_atribuicao',
  assignments: 'atribuicoes', atribuicoes: 'atribuicoes', hours: 'horas', horas: 'horas',
  deliberation: 'deliberacao', deliberacao: 'deliberacao', resolution: 'resolucao',
  justification: 'justificacao', tarefas: 'tarefas', dificuldades: 'dificuldades', realizacoes: 'realizacoes',
  melhorar: 'melhorar', positivos: 'positivos', missao: 'missao', objectivos: 'objetivos',
  responsabilidades: 'responsabilidades', responsavel: 'responsavel', niveis: 'niveis',
  dimensao_filhos: 'dimensao_filhos', vagas: 'vagas', cargo: 'cargo', chefia: 'chefia',

  // ── RH ────────────────────────────────────────────────────────────────────
  employee_id: ['colaborador_id', 'employees'], manager_employee_id: ['colaborador_gestor_id', 'employees'],
  responsavel_employee_id: ['colaborador_responsavel_id', 'employees'],
  chefia_employee_id: ['colaborador_chefia_id', 'employees'],
  avaliado_employee_id: ['colaborador_avaliado_id', 'employees'],
  avaliador_employee_id: ['colaborador_avaliador_id', 'employees'],
  role_id: ['cargo_funcao_id', 'roles'], org_type_id: ['tipo_organizacao_id', 'org_types'],
  org_unit_id: ['unidade_organica_id', 'org_units'], unit_id: ['unidade_organica_id', 'org_units'],
  org_position_id: ['posto_trabalho_id', 'org_positions'],
  reporta_a_position_id: ['posto_superior_id', 'org_positions'],
  infotype_id: ['infotipo_salarial_id', 'infotypes'],
  payroll_period_id: ['periodo_processamento_salarial_id', 'payroll_periods'],
  prod_period_id: ['periodo_produtividade_id', 'rh_prod_periods'],
  portal_request_id: ['pedido_portal_colaborador_id', 'rh_portal_requests'],
  vacation_id: ['plano_ferias_colaborador_id', 'rh_vacations'],
  ciclo_id: ['ciclo_avaliacao_id', 'rh_eval_cycles'],
  fecho_id: ['fecho_mensal_assiduidade_id', 'rh_attendance_closures'],
  contract_days_month: 'dias_contrato_mes', hours_per_day: 'horas_por_dia', work_days: 'dias_uteis_mes',
  worked_days: 'dias_trabalhados', dias: 'dias', dias_uteis: 'dias_uteis', horas_falta: 'horas_falta',
  remunerations: 'remuneracoes', is_retired: 'reformado', is_avencado: 'avencado', inss: 'numero_inss',
  irt: 'irt', sexo: 'sexo', data_nascimento: 'data_nascimento', estado_civil: 'estado_civil',
  nacionalidade: 'nacionalidade', naturalidade: 'naturalidade', provincia_naturalidade: 'provincia_naturalidade',
  documento_identificacao: 'documento_identificacao', documento_validade: 'documento_validade',
  data_admissao: 'data_admissao', emergencia_nome: 'emergencia_nome', emergencia_telefone: 'emergencia_telefone',
  emergencia_parentesco: 'emergencia_parentesco', habilitacao_maxima: 'habilitacao_maxima',
  parentesco: 'parentesco', dependente_fiscal: 'dependente_fiscal', formacao: 'formacao',
  ausencias_geradas: 'ausencias_geradas', origem_efectividade: 'origem_efetividade',
  origem_produtividade: 'origem_produtividade', produtividade: 'produtividade', registos_fecho: 'registos_fecho',
  ocorrencia: 'ocorrencia', motivo_reabertura: 'motivo_reabertura', direito: 'direito',
  bonificacao: 'bonificacao', criterios: 'criterios', peso: 'peso', pesos: 'pesos', comentario: 'comentario',
  feedback: 'feedback', participantes: 'participantes', max_pares: 'max_pares',
  minimo_anonimato: 'minimo_anonimato', abordagem: 'abordagem', ambito: 'ambito', apoio: 'apoio',
  acordos: 'acordos', comunicado: 'comunicado', disposicao: 'disposicao', metrica: 'metrica',
  reparticao: 'reparticao', resultado: 'resultado', sentido: 'sentido', textos: 'textos', corpo: 'corpo',
  assunto: 'assunto', prazos: 'prazos', rubric: 'rubrica',

  // ── Orçamento ─────────────────────────────────────────────────────────────
  budget_id: ['orcamento_anual_id', 'orc_budgets'], rubric_id: ['rubrica_orcamental_id', 'orc_rubrics'],
  versao_origem_id: ['versao_origem_id', 'orc_budgets'],

  // ── CRM ───────────────────────────────────────────────────────────────────
  account_id: ['conta_crm_id', 'crm_accounts'], contact_id: ['contacto_crm_id', 'crm_contacts'],
  opportunity_id: ['oportunidade_crm_id', 'crm_opportunities'], pipeline_id: ['funil_vendas_crm_id', 'crm_pipelines'],
  modelo_id: ['modelo_email_crm_id', 'crm_templates'], etapa_id: 'etapa_codigo', etapas: 'etapas',
  probabilidade: 'probabilidade', concorrente: 'concorrente', motivo_perda: 'motivo_perda', rejeicoes: 'rejeicoes',

  // ── Campos que só o código grava (docs/dicionario/campos_codigo_legado.json) ──
  // Faturação electrónica AGT (sales.fe_*)
  fe_avisos: 'fe_avisos', fe_documento: 'fe_documento', fe_envio: 'fe_envio', fe_erros: 'fe_erros',
  fe_estabelecimento: 'fe_estabelecimento', fe_estado: 'fe_estado', fe_numero: 'fe_numero', fe_pais: 'fe_pais',
  fe_regime: 'fe_regime', fe_selado: 'fe_selado', fe_selado_em: 'fe_selado_em', fe_serie: 'fe_serie',
  fe_serie_id: ['serie_faturacao_eletronica_id', 'fe_series'], fe_system_entry: 'fe_data_entrada_sistema',
  fe_tipo: 'fe_tipo', fe_validado_em: 'fe_validado_em', nc_motivo: 'motivo_nota_credito',
  agt_codigo: 'agt_codigo', agt_pedido_em: 'agt_pedido_em', agt_primeiro: 'agt_primeiro_numero',
  agt_quantidade: 'agt_quantidade', agt_ultimo: 'agt_ultimo_numero', proximo: 'proximo_numero',
  estabelecimento: 'estabelecimento', auto_emitir: 'auto_emitir',
  // Empresa: horas extra e moeda funcional
  he_limite_horas: 'he_limite_horas', he_percentagem_1: 'he_percentagem_1', he_percentagem_2: 'he_percentagem_2',
  functional_currency: 'moeda_funcional',
  // RH
  base_horaria: 'base_horaria', calculo_horas: 'calculo_horas', eval_bonus_id: ['bonificacao_avaliacao_id', 'rh_eval_bonus'],
  payroll_entry_id: ['linha_folha_salarial_id', 'payroll_entries'], absence_id: ['ausencia_falta_id', 'rh_absences'],
  alvo_employee_id: ['colaborador_alvo_id', 'employees'], avaliacao_id: 'avaliacao_id',
  letter_id: ['carta_pagamento_bancario_id', 'payment_letters'], actualizado_360_em: 'atualizado_360_em',
  arredondamento_min: 'arredondamento_min', assinante: 'assinante', cargo_assinante: 'cargo_assinante',
  autorizado_extra: 'autorizado_extra', avaliador: 'avaliador', avisos: 'avisos', avisos_360: 'avisos_360',
  calculado_em: 'calculado_em', calculado_por: 'calculado_por', classificacao: 'classificacao',
  classificacao_360: 'classificacao_360', comentario_colaborador: 'comentario_colaborador',
  componentes_360: 'componentes_360', confirmacao: 'confirmacao', conhecimento: 'conhecimento',
  contestacao: 'contestacao', curso: 'curso', data_avaliacao: 'data_avaliacao', instituicao: 'instituicao',
  ano_conclusao: 'ano_conclusao', nivel: 'nivel', nota: 'nota', nota_360: 'nota_360',
  plano_desenvolvimento: 'plano_desenvolvimento', pontos_fortes: 'pontos_fortes', pontos_melhorar: 'pontos_melhorar',
  pontuacao: 'pontuacao', pontuacao_criterios: 'pontuacao_criterios', pontuacao_objectivos: 'pontuacao_objetivos',
  peso_objectivos: 'peso_objetivos', respostas: 'respostas', justificada_em: 'justificada_em', justificada_por: 'justificada_por',
  remunerada: 'remunerada', modo_compensacao: 'modo_compensacao', limite_compensacao_h: 'limite_compensacao_h',
  relogio: 'relogio', feriados: 'feriados', tolerancia_min: 'tolerancia_min', minimo_dia_horas: 'minimo_dia_horas',
  extras_min_minutos: 'extras_min_minutos', extra_nao_util_exige_autorizacao: 'extra_nao_util_exige_autorizacao',
  reaberta_em: 'reaberta_em', reaberta_por: 'reaberta_por', texto: 'texto', title: 'titulo', local: 'local',
  // Aprovações, decisões e anulações (genéricos)
  approval_note: 'nota_aprovacao', approved_at: 'aprovado_em', approved_by: 'aprovado_por', aprovado_em: 'aprovado_em',
  aprovado_por: 'aprovado_por', decided_at: 'decidido_em', decided_by: 'decidido_por', decidido_por: 'decidido_por',
  decision_note: 'nota_decisao', nota_decisao: 'nota_decisao', rejected_at: 'rejeitado_em', rejected_by: 'rejeitado_por',
  rejection_reason: 'motivo_rejeicao', cancel_reason: 'motivo_cancelamento', cancelado_em: 'cancelado_em',
  cancelled_at: 'cancelado_em', cancelled_by: 'cancelado_por', anulado_em: 'anulado_em', anulado_por: 'anulado_por',
  executed_at: 'executado_em', executed_by: 'executado_por', expires_at: 'expira_em', requested_by: 'pedido_por',
  pedido_em: 'pedido_em', pedido_por: 'pedido_por', submetido_em: 'submetido_em', submetido_por: 'submetido_por',
  publicado_em: 'publicado_em', publicado_por: 'publicado_por', paid_at: 'pago_em', paid_by: 'pago_por',
  unposted_at: 'descontabilizado_em', unposted_by: 'descontabilizado_por', utilizado_em: 'utilizado_em',
  motivo: 'motivo', result: 'resultado', action_label: 'rotulo_acao', accao: 'acao',
  // Manutenção de dados (maintenance_requests — pedidos com aprovação dupla, js/manutencao.js)
  maint_company_id: ['empresa_id', 'companies'], scope: 'ambito', scope_company_name: 'nome_empresa_ambito',
  params: 'parametros', params_resumo: 'resumo_parametros', impact_at_request: 'impacto_no_pedido',
  impact_at_approval: 'impacto_na_aprovacao', impact_at_execution: 'impacto_na_execucao',
  // Contabilidade, tesouraria, câmbio
  account_nature: 'natureza_conta', account_third: 'conta_terceiro', bank_account_code: 'codigo_conta_bancaria',
  entry_state: 'estado_lancamento', fx_rounding: 'arredondamento_cambial', contra_currency: 'contra_moeda',
  contra_value_currency: 'contravalor_moeda', contra_value_kz: 'contravalor_kz', total_with_tax: 'total_com_imposto',
  commission_deducted: 'comissao_deduzida', commission_doc_id: 'documento_comissao_id',
  proof_amount: 'valor_comprovativo', proof_date: 'data_comprovativo', proof_ref: 'referencia_comprovativo',
  compensation: 'valor_compensacao', compensation_account: 'conta_compensacao', extras_account: 'conta_extras',
  extras_tax_rate: 'taxa_extras', manager_name: 'nome_gerente', manager_signed_at: 'assinado_gerente_em',
  signature_name: 'nome_assinatura', deliberation_cancelled: 'deliberacao_cancelada', ultima_data: 'ultima_data',
  regularizacao: 'regularizacao', termino: 'termino', base: 'base',
  // Lavandaria / POS
  claim_days: 'dias_reclamacao', declared_value: 'valor_declarado', delivery_fee: 'valor_taxa_entrega',
  pickup_fee: 'valor_taxa_recolha', piece_desc: 'descricao_peca', item_name: 'nome_item', servico: 'servico',
  storage_fee_enabled: 'taxa_armazenagem_ativa', storage_fee_pct_day: 'percentagem_armazenagem_dia',
  storage_free_days: 'dias_armazenagem_gratis', urgency_lead_factor: 'fator_prazo_urgencia', urgency_pct: 'percentagem_urgencia',
  invoice_on_advance: 'faturar_no_adiantamento', cf_advance_pct: 'percentagem_adiantamento', line_id: 'linha_pedido_id',
  // Orçamento
  controlo: 'controlo', driver: 'indutor', cambial_pct: 'cambial_pct', variavel_pct: 'variavel_pct', saldo_inicial: 'saldo_inicial',
  substituido_em: 'substituido_em', substituido_por_id: ['substituido_por_id', 'orc_budgets'], prazo_contributo: 'prazo_contributo',
  consolidado_em: 'consolidado_em', consolidado_por: 'consolidado_por', consolidado_ids: 'consolidado_ids',
  mes_ref: 'mes_referencia', revisao: 'revisao', crescimento_pct: 'crescimento_pct', revisao_origem_id: ['revisao_origem_id', 'orc_forecasts'],
  forecast_id: ['previsao_orcamental_id', 'orc_forecasts'], variaveis: 'variaveis', ajustes: 'ajustes', doc: 'documento',
  chave_doc: 'chave_documento', data_doc: 'data_documento', orcado: 'valor_orcado', consumido: 'valor_consumido',
  pct: 'percentagem', excesso: 'valor_excesso', autoaprovado: 'autoaprovado', contingencia: 'contingencia',
  // Projectos
  team_member_id: ['membro_equipa_projeto_id', 'project_team_members'], documento_url: 'documento_url', origem_nome: 'origem_nome',
  // CRM
  motivos_perda: 'motivos_perda', origens: 'origens', dias_sem_actividade: 'dias_sem_atividade',
  prazo_pagamento_dias: 'prazo_pagamento_dias', sequencia_id: ['sequencia_campanha_id', 'crm_sequences'], passos: 'passos',
};

// Destinos que dependem da tabela. Chave: tabela legado -> { coluna_legado: destino }.
// Tipos impostos quando a inferência a partir dos dados não serve (valores sujos no legado).
export const TIPOS_FORCADOS = {
  'audit_logs.company_id': 'bigint',
  'infotypes.calculo_horas': 'varchar(10)',
  'org_units.utilizador_responsavel': 'varchar(100)',
  // RH parte 3b: avaliação (tabelas vazias no backup — tipos do código estavam errados)
  'rh_evaluations.ano': 'integer', 'rh_evaluations.periodo': 'varchar(10)', 'rh_evaluations.criterios': 'jsonb', 'rh_evaluations.objectivos': 'jsonb',
  'rh_evaluations.peso_objectivos': 'numeric(5,2)', 'rh_evaluations.pontuacao': 'numeric(5,2)', 'rh_evaluations.pontuacao_criterios': 'numeric(5,2)',
  'rh_evaluations.pontuacao_objectivos': 'numeric(5,2)', 'rh_evaluations.classificacao': 'varchar(30)', 'rh_evaluations.status': 'varchar(20)',
  'rh_evaluations.pontos_fortes': 'text', 'rh_evaluations.pontos_melhorar': 'text', 'rh_evaluations.plano_desenvolvimento': 'text',
  'rh_evaluations.nota_360': 'numeric(5,2)', 'rh_evaluations.classificacao_360': 'varchar(30)', 'rh_evaluations.componentes_360': 'jsonb',
  'rh_evaluations.avisos_360': 'jsonb', 'rh_evaluations.conhecimento': 'jsonb', 'rh_evaluations.contestacao': 'jsonb',
  'rh_evaluation_items.meta': 'numeric(15,3)',
  'rh_eval_bonus.metodo': 'varchar(20)', 'rh_eval_bonus.classificacao': 'varchar(30)', 'rh_eval_bonus.nota': 'numeric(5,2)', 'rh_eval_bonus.base': 'numeric(15,2)',
  'rh_eval_bonus.estado': 'varchar(20)', 'rh_eval_bonus.avaliacao_id': 'bigint', 'rh_eval_bonus.period_id': 'bigint',
  'rh_eval_feedback.acordos': 'text',
  'rh_upward_participation.ano': 'integer', 'rh_upward_participation.periodo': 'varchar(10)',
  'rh_upward_responses.ano': 'integer', 'rh_upward_responses.periodo': 'varchar(10)', 'rh_upward_responses.respostas': 'jsonb', 'rh_doc_templates.codigo': 'varchar(50)',
  // RH parte 2 (tabelas quase sem dados no backup: tipos inferidos do código estavam errados)
  'rh_attendance_config.dias_uteis': 'jsonb', 'rh_attendance_config.feriados': 'jsonb', 'rh_attendance_config.arredondamento_min': 'integer',
  'rh_attendance_config.modo_compensacao': 'varchar(10)', 'rh_attendance_config.extra_nao_util_exige_autorizacao': 'boolean',
  'rh_attendance.autorizado_extra': 'boolean',
  'rh_absences.avisos': 'jsonb', 'rh_absences.tipo': 'varchar(40)', 'rh_absences.remunerada': 'varchar(20)', 'rh_absences.documento_url': 'text',
  'rh_absences.nota_decisao': 'text',
  'rh_prod_items.minimo': 'numeric(15,3)', 'rh_prod_items.maximo': 'numeric(15,3)', 'rh_prod_items.preco_unitario': 'numeric(15,4)',
  'rh_productivity.preco_unitario': 'numeric(15,4)', 'rh_productivity.data': 'date',   // '' (automático), EXTRA, FALTA ou NAO — texto, não número
  // Câmbios: 6 casas decimais (o legado guardava até 6; numeric(9,4) truncava e limitava a 99 999)
  'exchange_rates.rate': 'numeric(18,6)', 'exchange_rates.created_by': 'varchar(100)', 'exchange_rates.updated_by': 'varchar(100)',
  'exchange_rates.source': 'varchar(50)',
  'audit_logs.user': 'varchar(100)',      // 18 linhas gravaram o objecto de sessão: extrai-se .username
  'audit_logs.record_id': 'varchar(255)', // inteiros, textos e 72 arrays ([15,91] -> "15,91")
  'users.allowed_companies': 'jsonb',     // normalizado para utilizador_empresa (pivô)
  'users.colaboradores': 'jsonb',         // {empresa_id: colaborador_id} -> utilizador_empresa.colaborador_id
  'treasury_items.orig_doc_date': 'varchar(50)',
  'journal_lines.doc_date': 'date',             // data de competência (directiva 3.2); 52 valores traziam hora
  'recycled_journal_lines.doc_date': 'date',
  // Séries de facturação (tabela sem dados no backup: tipos definidos aqui, não inferidos)
  'fe_series.codigo': 'varchar(30)', 'fe_series.tipo': 'varchar(5)', 'fe_series.ano': 'integer', 'fe_series.origem': 'varchar(30)',
  'fe_series.estado': 'varchar(20)', 'fe_series.ultima_data': 'date', 'fe_series.estabelecimento': 'varchar(20)',
  'fe_series.agt_codigo': 'varchar(60)', 'fe_series.agt_primeiro': 'integer', 'fe_series.agt_ultimo': 'integer',
  'fe_series.agt_quantidade': 'integer', 'fe_series.proximo': 'integer',
  // Facturação electrónica nas vendas (campos só do código: tipos definidos aqui)
  'sales.fe_documento': 'jsonb', 'sales.fe_erros': 'jsonb', 'sales.fe_avisos': 'jsonb', 'sales.fe_envio': 'jsonb',
  'sales.fe_estado': 'varchar(20)', 'sales.fe_tipo': 'varchar(5)', 'sales.fe_serie': 'varchar(50)', 'sales.fe_numero': 'integer',
  'sales.fe_estabelecimento': 'varchar(20)', 'sales.delivery_date': 'date', 'sale_items.notes': 'text', 'sale_items.description': 'text', // mistura datas com números de documento ("FT FA12026/761")
};

export const SOBREPOSICOES = {
  // Nas empresas 10 e 18 (antigas linhas "dado mestre") sobraram colunas de enchimento sem significado.
  companies: { company_id: null, consolidation_run_id: ['execucao_consolidacao_id', 'consolidation_runs'],
    description: null, value: null, total_value: null, quantity: null, doc_number: null, code: null,
    date: null, doc_date: null, entry_date: null, reference: null },
  employees: { name: 'nome_completo' },
  // infotypes.inss é a flag «sujeito a INSS» da rubrica (não o n.º de segurança social do colaborador)
  infotypes: { inss: 'sujeito_inss' },
  // fecho da assiduidade e período de produtividade: period_id é o processamento salarial onde foram lançados
  rh_attendance_closures: { period_id: ['periodo_processamento_salarial_id', 'payroll_periods'] },
  rh_prod_periods: { period_id: ['periodo_processamento_salarial_id', 'payroll_periods'] },
  rh_eval_bonus: { period_id: ['periodo_processamento_salarial_id', 'payroll_periods'], avaliacao_id: ['avaliacao_desempenho_id', 'rh_evaluations'] },
  purchase_contract_milestones: { contract_id: ['contrato_fornecedor_id', 'purchase_contracts'] },
  lav_claims: { order_id: ['pedido_lavandaria_id', 'lav_orders'] },
  project_documents: { type_id: ['tipo_documento_id', 'document_types'] },
  sales: { date: 'data_emissao', doc_date: 'data_emissao' /* directiva, secção 3.1 */ },
  audit_logs: { company_id: 'empresa_id' /* sem FK: a auditoria sobrevive a empresas eliminadas */ },
  products: { category_id: ['categoria_produto_id', 'product_categories'] },
  fixed_assets: { category_id: ['categoria_ativo_id', 'asset_categories'] },
  treasury_items: { doc_id: ['documento_tesouraria_id', 'treasury_documents'] },
  delivery_notes: { entity_id: ['terceiro_id', 'third_parties'] },
  documents: { entity_id: 'entidade_id', type_id: ['tipo_documento_id', 'document_types'] },
  delivery_items: { delivery_id: 'guia_id' /* polimórfico: guias_saida ou rececoes_compra (ver notas) */ },
  purchase_items: { parent_id: 'documento_origem_id', order_id: ['encomenda_compra_id', 'purchase_orders'] },
  purchase_deliveries: { order_id: ['encomenda_compra_id', 'purchase_orders'] },
  purchase_invoices: { order_id: ['encomenda_compra_id', 'purchase_orders'] },
  purchase_contracts: { order_id: ['encomenda_compra_id', 'purchase_orders'] },
  purchase_orders: { contract_id: ['contrato_fornecedor_id', 'purchase_contracts'] },
  lav_payments: { order_id: ['pedido_lavandaria_id', 'lav_orders'], session_id: ['sessao_pos_id', 'pos_sessions'] },
  cash_lines: { session_id: ['sessao_caixa_id', 'cash_sessions'] },
  inventory_session_lines: { session_id: ['sessao_inventario_id', 'inventory_sessions'] },
  pos_settlements: { session_id: ['sessao_pos_id', 'pos_sessions'] },
  hotel_stays: { session_id: ['sessao_pos_id', 'pos_sessions'] },
  ad_postings: { item_id: ['item_acrescimo_diferimento_id', 'ad_items'] },
  rh_productivity: { item_id: ['item_produtividade_id', 'rh_prod_items'] },
  orc_budgets: { pai_id: ['orcamento_pai_id', 'orc_budgets'] },
  org_units: { pai_id: ['unidade_organica_pai_id', 'org_units'] },
  business_units: { parent_id: ['unidade_negocio_pai_id', 'business_units'] },
  project_org_nodes: { parent_id: ['no_pai_id', 'project_org_nodes'] },
  recycled_journal_lines: { original_id: 'lancamento_original_id' /* o original foi eliminado: sem FK */ },
  reconciliation_matches: { internal_id: ['lancamento_contabil_id', 'journal_lines'], external_id: ['linha_extrato_bancario_id', 'bank_statement_lines'] },
  payroll_entries: { period_id: ['periodo_processamento_salarial_id', 'payroll_periods'] },
  journal_lines: { period_id: 'periodo_id' },
  asset_depreciations: { period_id: 'periodo_codigo' },
};
