<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * audit_logs (legado, 106 221 linhas reais) -> logs_auditoria, particionada por ano (RANGE em ocorrido_em).
 *
 * Decisões:
 *  - Sem FK em empresa_id/utilizador_id: a auditoria é histórica e imutável e tem de sobreviver à
 *    eliminação de empresas e utilizadores (o backup tem logs das empresas 21 e 11, que já não existem).
 *  - PK (id, ocorrido_em): exigência do PostgreSQL para tabelas particionadas.
 *  - id GENERATED BY DEFAULT AS IDENTITY: permite preservar os ids do legado no ETL.
 *  - Partição DEFAULT recolhe datas fora dos anos criados; `erp:auditoria:particoes` cria os anos seguintes.
 */
return new class extends Migration
{
    public function up(): void
    {
        DB::statement(<<<'SQL'
            CREATE TABLE logs_auditoria (
                id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
                empresa_id       BIGINT NULL,
                utilizador_id    BIGINT NULL,
                nome_utilizador  VARCHAR(100) NULL,
                ocorrido_em      TIMESTAMPTZ NOT NULL DEFAULT now(),
                modulo           VARCHAR(100) NOT NULL,
                acao             VARCHAR(100) NOT NULL,
                tabela           VARCHAR(100) NULL,
                registo_id       VARCHAR(255) NULL,
                detalhes         TEXT NULL,
                dados_anteriores JSONB NULL,
                dados_novos      JSONB NULL,
                endereco_ip      VARCHAR(45) NULL,
                agente_utilizador TEXT NULL,
                PRIMARY KEY (id, ocorrido_em)
            ) PARTITION BY RANGE (ocorrido_em)
        SQL);

        foreach (config('erp.auditoria.anos_particoes') as $ano) {
            $seguinte = $ano + 1;
            DB::statement("CREATE TABLE logs_auditoria_{$ano} PARTITION OF logs_auditoria
                           FOR VALUES FROM ('{$ano}-01-01 00:00:00+00') TO ('{$seguinte}-01-01 00:00:00+00')");
        }
        DB::statement('CREATE TABLE logs_auditoria_padrao PARTITION OF logs_auditoria DEFAULT');

        DB::statement('CREATE INDEX ix_logs_auditoria_empresa_data ON logs_auditoria (empresa_id, ocorrido_em DESC)');
        DB::statement('CREATE INDEX ix_logs_auditoria_empresa_modulo ON logs_auditoria (empresa_id, modulo, ocorrido_em DESC)');
        DB::statement('CREATE INDEX ix_logs_auditoria_registo ON logs_auditoria (tabela, registo_id)');
        DB::statement('CREATE INDEX ix_logs_auditoria_utilizador ON logs_auditoria (utilizador_id, ocorrido_em DESC)');
    }

    public function down(): void
    {
        DB::statement('DROP TABLE IF EXISTS logs_auditoria CASCADE');
    }
};
